import numpy as np
print('---------------------------------------------------')
print("Using array to define an array")
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('---------------------------------------------------')
print("SubArray")
print(a[0])
print('---------------------------------------------------')
print("Using arange to define array from start to end")
b=np.arange(1,10)
print(b)
print('---------------------------------------------------')
print("Printing Zeros or ones")
c=np.zeros([3,3])
d=np.ones([3,3],dtype=int)
print(c)
print(d)
print('---------------------------------------------------')
print("Linspace, linear data")
e=np.linspace(0,10,6,True,True,dtype=int)
print(e)
print('---------------------------------------------------')
print("Concatenated array")
f=np.concatenate([a,d],axis=1)
print(f)
print("Array size(No of elements), dimension, shape")
print(f'Dimension{f.ndim}')
print(f'Size{f.size}')
print(f'Shape{f.shape}')
print('---------------------------------------------------')
print('Reshaping array(Not transpose, element wise pick and posiitioning')
print(f.reshape(6,3))
print('---------------------------------------------------')
print('Adding axis')
g=np.arange(6)
h=g[np.newaxis,:]
i=h.reshape(3,2)
print(i)
print('---------------------------------------------------')
print('Splicing')
print(i[0])
print(i[1,1])
print(i[:2:1,:1:])




